### ISSUE TITLE
Xdebug host is not discovered correctly

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon#1088]
**Describe the bug**
When `XDEBUG_ENABLE: "true"` is specified, the `xdebug. remote_host` is always set to `172.22.0.1`. 

Running the command from https://github.com/amazeeio/lagoon/blob/master/images/php/fpm/entrypoints/60-php-xdebug.sh#L6 _after_ container started returns correct results.

It looks like the timeout is too low to get this command running correctly during container starting.

**To Reproduce**
Steps to reproduce the behavior on MacOS:
1. Set `XDEBUG_ENABLE: "true"` in `docker-compose.yml`.
2. `docker-compose up -d --build`
3. Create a page with `phpinfo()` and run it.
4. Check the value of `xdebug.remote_host`. It will be `172.22.0.1`. 

**Expected behavior**
The value of `xdebug.remote_host` should be `docker.for.mac.localhost`.

It is possible to override this by setting `DOCKERHOST: "docker.for.mac.localhost"` in `docker-compose.yml`, but this defeats the purpose of the auto-discovery mechanism in https://github.com/amazeeio/lagoon/blob/master/images/php/fpm/entrypoints/60-php-xdebug.sh.

**Comment by tamasd** [comment]
`docker.for.mac.localhost` and `docker.for.win.localhost` are deprecated, the correct value for both platforms is `host.docker.internal`

**Comment by AlexSkrypnyk** [comment]
@tamasd prooflink?

**Comment by tamasd** [comment]
I haven't found the exact change (only a [reddit post](https://www.reddit.com/r/docker/comments/87ln1e/good_news_hostdockerinternal_resolves_to_host_on/) from a year ago), but both the [Windows](https://docs.docker.com/docker-for-windows/networking/) and [Mac](https://docs.docker.com/docker-for-mac/networking/) documentation only mentions `host.docker.internal`, and not the `docker.for.*.localhost` addresses.

**Comment by AlexSkrypnyk** [comment]
the `host.docker.internal` could be correct, but in this case - the problem is not with the value but rather how it is set. The auto-discovery mechanism does not work as expected.

**Comment by sonnykt** [comment]
The special DNS name `host.docker.internal` was available from Docker 18.03: https://docs.docker.com/docker-for-mac/networking/

**Comment by luksak** [comment]
Setting `DOCKERHOST: host.docker.internal` works for me.

**Comment by AlexSkrypnyk** [comment]
@sonnykt @luksak this issue is not about how to set the value of `DOCKERHOST` and that it works. It is about the auto-discovery of this value and this still does not work.

**Comment by AlexSkrypnyk** [comment]
@Schnitzel can this get some attention please. Downstream projects (GovCMS SaaS, for example) are not able to use Xdebug because they are not aware of this issue (their `remote_host` is never autodiscovered correctly and is set to the IP of container). Moreover, they cannot modify `docker-compose.yml` file to add `DOCKERHOST: host.docker.internal` line (as it is locked). Thanks

**Comment by Schnitzel** [comment]
@AlexSkrypnyk 
so would changing `docker.for.mac.localhost` to `host.docker.internal` in here
https://github.com/amazeeio/lagoon/blob/master/images/php/fpm/entrypoints/60-php-xdebug.sh#L6
solve the problem?

**Comment by AlexSkrypnyk** [comment]
@Schnitzel no, there are actually 2 problems:
1. the timeout - it is not enough time for `get_dockerhost()` to receive a response (what the original ticket is about), so it defaults to the default gateway.
2. The value `docker.for.mac.localhost`, `docker.for.win.localhost` etc. is deprecated and `host.docker.internal` should be used instead, which (possibly) makes this whole function obsolete - setting `DOCKERHOST` to `host.docker.internal` should solve it for all platforms.

From docs:
https://docs.docker.com/docker-for-windows/networking/

> I WANT TO CONNECT FROM A CONTAINER TO A SERVICE ON THE HOST
The host has a changing IP address (or none if you have no network access). From 18.03 onwards our recommendation is to connect to the special DNS name `host.docker.internal`, which resolves to the internal IP address used by the host. This is for development purpose and will not work in a production environment outside of Docker Desktop for Windows.
The gateway is also reachable as `gateway.docker.internal`.

and  https://docs.docker.com/docker-for-mac/networking/


>I WANT TO CONNECT FROM A CONTAINER TO A SERVICE ON THE HOST
The host has a changing IP address (or none if you have no network access). From 18.03 onwards our recommendation is to connect to the special DNS name `host.docker.internal`, which resolves to the internal IP address used by the host. This is for development purpose and will not work in a production environment outside of Docker Desktop for Mac.
The gateway is also reachable as `gateway.docker.internal`.

**Comment by Schnitzel** [comment]
I did some research myself and it seems that the problem is actually somewhere completely different:

1. `docker.for.mac.localhost` still works even with the newest Docker for Mac Version 2.1.0.3 (Docker Version: 19.03.2):
```
$ ping docker.for.mac.localhost
PING docker.for.mac.localhost (192.168.65.2): 56 data bytes
64 bytes from 192.168.65.2: seq=0 ttl=37 time=0.373 ms```

and `host.docker.internal` works as well:
```ping host.docker.internal
PING host.docker.internal (192.168.65.2): 56 data bytes
64 bytes from 192.168.65.2: seq=0 ttl=37 time=0.502 ms```

2. `host.docker.internal` does **NOT** work on Linux systems, so just setting `DOCKERHOST` to `host.docker.internal` would not work on Linux systems, and we still need the `route -n | awk '/UG[ \t]/{print $2}'` system
3. The actual problem is that `busybox timeout -t 1` is not working anymore on the newest alpine that PHP has running inside, it fails with:
```
# busybox timeout -t 1
timeout: unrecognized option: t```
4. Some `docker-compose.yml` version doe now set the running user to `1000`: https://github.com/amazeeio/drupal-example/blob/master/docker-compose.yml#L23-L26 which means that it's not running as root and `ping` can only be used under the User root, so we need to find another way to check if the host is reachable. But I think we could do this via nslookup:

os x:
```$ busybox timeout 1 nslookup host.docker.internal
nslookup: can't resolve '(null)': Name does not resolve

Name:      host.docker.internal
Address 1: 192.168.65.2```

linux:
```
/ # busybox timeout 1 nslookup host.docker.internal
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'host.docker.internal': Name does not resolve
```

so we would need a PR that: 
1. changes the `ping` tests to `nslookup` tests, like `busybox timeout 1 nslookup host.docker.internal`
2. combines the windows and mac tests into one for `host.docker.internal`
3. removes the check for `172.16.172.16` (it's not necessary anymore)
4. keeps the default gateway check

I don't have time right now to work on this, but this should be a fairly easy fix

**Comment by smlx** [comment]
Just wanted to note, `host.docker.internal` should be supported on linux soon too via https://github.com/moby/moby/pull/40007

**Comment by fubarhouse** [comment]
I've got a commit ready to support the changes @Schnitzel has raised.

**Comment by AlexSkrypnyk** [comment]
@Schnitzel 
I have encountered this issue again on various projects. The timeout increase issue described above still exists and was never addressed in the PR that closed this issue; that PR only fixed the `timeout` option, but not the value. 1 second is not enough to discover the host IP. 
https://github.com/amazeeio/lagoon/blob/master/images/php/fpm/entrypoints/60-php-xdebug.sh#L6

Could you please advise if this issue should be re-opened or a new one created? 

Currently I have to use the workaround that I've used before this issue was created (so it is not solved): adding `DOCKERHOST: ${DOCKERHOST:-host.docker.internal}` to `docker-compose.yml`.

**Comment by Schnitzel** [comment]
@AlexSkrypnyk 
interesting, are you sure that 1 second is not enough? In my tests the resolution took max 200ms, you can test with `time busybox nslookup host.docker.internal` to check the length of a possible resolution.

If we need to give it more time I'm happy to add that, but there might be another issue with resolution all together?

**Comment by rocketeerbkw** [comment]
I spent the last couple hours trying to get xdebug and vscode working and I think I've narrowed it down this this same issue. I'm also seeing my `xdebug.remote_host` was always set to the gateway IP of `172.24.0.1` and wasn't connecting. I think i've narrowed it down to the fact that `nslookup` returns an exit code of `1`, so the `if` statement at https://github.com/amazeeio/lagoon/blob/master/images/php/fpm/entrypoints/60-php-xdebug.sh#L6 is always skipped.

```bash
[drupal-example]php:/app$ nslookup host.docker.internal
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	host.docker.internal
Address: 192.168.65.2

** server can't find host.docker.internal: NXDOMAIN

[drupal-example]php:/app$ echo $?
1
```

I'm not sure why that is, maybe because of the error `** server can't find host.docker.internal: NXDOMAIN`? If I lookup a real domain it returns error code `0`.

```bash
[drupal-example]php:/app$ nslookup google.com
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	google.com
Address: 2607:f8b0:4000:817::200e

Non-authoritative answer:
Name:	google.com
Address: 172.217.1.238

[drupal-example]php:/app$ echo $?
0
```

It doesn't seem to be a timeout issue IMO.

**Comment by iijiang** [comment]
https://github.com/uselagoon/lagoon/issues/519#issuecomment-917498085
not sure the problem, looks like I still have this problem.
