### ISSUE TITLE
API: Refactor user role Middleware

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#109]

**Comment by ryyppy** [comment]
I introduced role based data access for non-admin users. So how does this work?

**Admin Users**:
If the server receives an admin token, the middleware will do nothing special, just passes the admin role in the credentials context as before.

**Non Admin Users**:
If the server receives a token with a non-admin role, it will extract the sshKey attribute of the payload and query the database (`permission` table view).

This query returns a `customerId` and also a `projects` array (I thought we would need this, but it turned out we don't even use it right now). This information is passed in the `credentials` context as well.

All the `dao.js` functions are mostly using this `customerId` credentials to add additional `WHERE` conditions, locking the queried data to the specific customer. This has certain advantages, e.g. we can now do graphql based query `allProjects`, which is then scoped to the given authenticated customer. 

**Not included**:
These changes are enabled for read operations... ADD / DELETE / TRUNCATE are not yet supported.

Tracking Branch: #128

**Comment by Schnitzel** [comment]
I consider this done, created more tickets for the other operations:
https://github.com/amazeeio/lagoon/issues/154
https://github.com/amazeeio/lagoon/issues/155
https://github.com/amazeeio/lagoon/issues/156
