### ISSUE TITLE
Switch from mariasql to mariadb

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1270]
Looks like MariaSQL is not maintained anymore and also doesn't build on node 12 anymore, we should switch to https://www.npmjs.com/package/mariadb

**Comment by blazeyo** [comment]
I've checked all the references to _mariasql_ and _sqlClient_ (496 results in 34 files) in the codebase and it turns out that all of them end up in either [query](https://github.com/amazeeio/lagoon/blob/master/services/api/src/util/db.js#L85) or prepare functions from _services/api/src/util/db.js_. This is most likely good news because it should make the swap relatively easy. I'll be experimenting with that now.

One things struck me during this review. If all the ~490 appearances of the text `sqlClient` end up in the same method, does it really make sense to pass them around? It looks like getting the client in the query/prepare methods would let us remove hundreds of lines of code (literally). Would it make sense to do that along with the package swap?

Here's a breakdown of files mentioning sqlClient:
- apolloServer.js
  - first, the client is passed on to `getGrantForKeycloakToken` from auth.js which isn't using it
  - then a new client is passed to `getCredentialsForLegacyToken` thich isn't using it either
  - then another client instance is created and put in the context (returned)
- authMiddleware.js
  - same as above, the client is only instantiated to be passed to `getGrantForKeycloakToken` and `getCredentialsForLegacyToken`. Both don't use it.
- auth.js
  - holds `getGrantForKeycloakToken` and `getCredentialsForLegacyToken`
- pubSub.js
  - the sqlClient is needed for the db/query function
- resolvers/index.js
  - `sqlClient: MariaSQL` used in a comment (flow type definition)
- sync-groups-opendistro-security.ts
  - the sqlClient is passed to opendistroSecurity.js, which passes it to project/helpers.js which passes it to the db/query function
- consumers-to-groups.js
  - instantiates the sqlClient and passes it to db/query and db/prepare
- projects.ts
  - instantiates the sqlClient and passes it to db/query and db/prepare
- reset-project-keys.ts
  - instantiates the sqlClient and passes it to db/query and db/prepare
- user.ts
  - instantiates the sqlClient and passes it to db/query and db/prepare
- backup/resolvers.js
  - uses the environment/helpers.js (which use db/query)
  - calls db/query directly
- deployment/helpers.js
  - uses the environment/helpers.js (which use db/query)
  - calls db/query directly
- backup/resolvers.js
  - uses the environment, deployment and project helpers (all of which use db/query)
  - calls db/prepare and db/query directly
- env-variables/resolvers.js
  - uses the environment helpers (which use db/query)
  - calls db/prepare and db/query directly
- environment/helpers.js
  - uses db/query and calls project/helpers.js
- environment/resolvers.js
  - calls db/prepare and db/query directly
  - uses the environment helpers (which use db/query)
- environment/validators.js
  - calls db/prepare and db/query directly
- file/resolver.js
  - calls db/query directly
- opendistrosecurity.js
  - uses the project/helpers.js (which use db/query)
- group/resolvers.ts
  - uses project/helpers.js (which use db/query)
  - uses opendistrosecurity.js (which uses the project/helpers.js which call db/query)
- notification/helpers.js
  - calls db/query directly
- notification/resolvers.js
  - calls db/prepare and db/query directly
  - uses project/helpers.js and notification/helpers.js (which use db/query)
- openshift/resolvers.js
  - calls db/prepare and db/query directly
- project/helpers.js
  - calls db/query directly
- project/resolvers.js
  - calls db/prepare and db/query directly
  - uses project/helpers.js and notification/helpers.js (which use db/query)
  - uses opendistrosecurity.js (which uses project/helpers.js)
- sshKey/resolvers.js
  - calls db/prepare and db/query directly
- task/helpers.js
  - calls db/query directly
- task/resolvers.js
  - uses the environment and task helpers (which use db/query)
  - calls db/prepare and db/query directly
  - uses the environment/validators.js (db/query and db/prepare)
- user/resolvers.js
  - calls db/query directly
- keys.js
  - calls db/query directly

**Comment by rocketeerbkw** [comment]
Yes, switching sql clients is a good opportunity to refactor, and I think that the new client would be an improvement but there are some considerations.

`MariaSQL` has a shared, non-asynchronous query queue. Previously we used a single, global instance but that meant every query for every request was placed into a single queue and caused issues, see #920. This is the reason `sqlClient` is instantiated and passed to all resolvers via apollo server context (one client per api request).

I've only looked briefly but it appears that the MariaDB node.js connector has a proper connection pool. So it would probably make sense to come up with some api that can abstract this out for every query. The current `query`/`prepare` methods are very MariaSQL centric though and I probably would refactor all that as well.

So: 1) We really need to test that we can switch to a "singleton" with a pool and not have same problems as #920 2) Even though it looks dirty, passing sqlClient around is proper dependency injection and I don't think a connection-handling-`query` with direct in-function calls is the "right way." We don't have unit tests now, but that would make it impossible to add.

We're moving away from having all the business logic in the resolver functions (see models/group, models/user), so those will become skinnier and have less passing.

**Comment by tobybellwood** [comment]
Now that Node:10 is [Maintenance LTS](https://nodejs.org/en/about/releases/) - we should look to switch to Node:14 - which will force this change.

**Comment by tobybellwood** [comment]
With the release of alpine 3.13 - the need to move away from node:10 based images has increased.  Technically the Alpine 3.11 EOL is 2021-11-01 - but the upstream node 10 images are in maintenance only until 2021-05-01

**Comment by dan2k3k4** [comment]
I think we could aim to do a first pass of replacing the instances of `mariasql` with `mariadb` along with the required API changes. Then we could look into refactoring out a better solution or do a complete rewrite?

**Comment by rocketeerbkw** [comment]
In addition to not working on supported versions of node, it looks like our api is crashing a lot due to https://github.com/mscdex/node-mariasql/issues/73
