### ISSUE TITLE
Lagoon UI: Display the currently running tag

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1384]
**Describe the feature**

It would be handy to know what version of Lagoon is running in the UI. Currently the only way to know what version you are running is buried deep inside OpenShift.

Perhaps link to the release notes as well for the released tag for bonus points.

Perhaps something like

![image](https://user-images.githubusercontent.com/10605846/68266046-c35c3480-00b2-11ea-9863-76b49cbc60cb.png)

**Comment by shreddedbacon** [comment]
Would be handy if this also was backed by a graphql query like `getLagoonVersion` ?

**Comment by tobybellwood** [comment]
given that LAGOON_VERSION is stored in each pod as a variable, maybe we just need to surface the most relevant one (noting that because of hotfixes, _some_ images may be ahead of others.  Generally the API should be used though.  Having a link to release notes could be via predetermined URLs to not require hardcoding - such as the gitlab tags?
https://github.com/amazeeio/lagoon/releases/tag/v1.2.0
https://github.com/amazeeio/lagoon/releases/tag/{$LAGOON_VERSION}

**Comment by shreddedbacon** [comment]
The reason for a query in the API is also beneficial for the CLI, as then we can perform a version verification to do certain things if the API doesn't support the request we are about to throw at it.
