### ISSUE TITLE
Routes longer than 63 chars not correctly created

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#1389]
**Describe the bug**
Due to an hard limit of Openshift, routes longer than 64 chars are not accepted.
Lagoon automatically create `safe branch` variable that's a branch name shorter than 64 chars.
Accordly to this safe branch, Lagoon should create a route shorter than 64 chars but it doesn't happen.

Here the piece of code that creates `SAFE_BRANCH` https://github.com/amazeeio/lagoon/blob/master/services/openshiftbuilddeploy/src/index.js#L51-L57

**To Reproduce**
1. Create a project with a branch name longer than 64 chars

**Expected behavior**
An Openshift route compliant with 64 chars limits.

**Comment by Schnitzel** [comment]
the problem is that the name of the service is prefixed to the route name, so for nginx the route name ends up being: `nginx-$SAFE_BRANCH` which is then longer than 63 chars, as `SAFE_BRANCH` is already 63 chars.

so maybe `SAFE_BRANCH` should be created with max 53 characters, so there is 10 characters left for the servicename? (this is though a guessing game, as people could call their services with something longer than 10 characters again)

**Comment by seanhamlin** [comment]
Just spotted this in the wild

```
router_controller.go:250] host name validation errors: spec.host: Invalid value: "nginx-royalbanana-feature-config-remove-shield-creds-from-dev.cluster.amazee.io": must be no more than 63 characters
```

Perhaps something like the DBaaS operator does, pseudo code:

```
if route > 63 characters
  truncate route to 57 characters and append a '-' followed by a 5 char hash of route
```

e.g. 

80 characters

```
nginx-royalbanana-feature-config-remove-shield-creds-from-dev.cluster.amazee.io
```

After the logic (63 characters)

```
nginx-royalbanana-feature-config-remov-15399.cluster.amazee.io
```

**Comment by tobybellwood** [comment]
this is now handled in the remote-controller
