### ISSUE TITLE
example on how to send notification email if cron fails

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1653]
as we don't have notifications based on cronjobs yet (will be implemented in https://github.com/amazeeio/lagoon/issues/618) we could create a simple bash wrapper around commands like `drush cron` which would check the return code of the command and send an email to the owner of the site.
All of this should be built in pure bash and not with any changes in lagoon.

**Comment by shreddedbacon** [comment]
# Send email for failing cron
This is an example on how to send an email when cron fails, capturing the error output from the command and sending it as the body

Modify the following variables in the script to suit
* `TO_ADDR` to change the recipients
* `FROM_ADDR` to change the sender
* `SUBJECT` to change the subject
* `COMMAND` to change the command that is run

### Create `cron-email.sh`
Put this script somewhere in your repository so that it can be added to your CLI containers dockerfile
```
#!/bin/bash
ERRFILE=$(mktemp)
TO_ADDR="recipient1@domain.com,recipient2@domain.com"
FROM_ADDR="NOREPLY <noreply@domain.com>"
SUBJECT="Drush cron failure"
# define the command to run here, replace `drush cron` with whichever command you need
COMMAND="drush cron"
if ($COMMAND 2> >(tee $ERRFILE)) ; then
echo "Cron exited clean"
else
echo "Cron failed, sending email"
ERROR=$(<$ERRFILE)
sendmail $TO_ADDR <<EOF
To: $TO_ADDR
Subject: $SUBJECT
From: $FROM_ADDR

Error was:
$ERROR
EOF
rm $ERRFILE
fi
```

### Make it executable
```
chmod +x cron-email.sh
```

### Add the script to `Dockerfile.cli`
Make sure you add the script to the dockerfile if it isn't already in a location that gets added to the container.
```
COPY cron-email.sh /app/cron-email.sh
```

### Change cron in `.lagoon.yml`
Update the cronjob in your `.lagoon.yml` file to change the `command:` to the path of the script (example: `/app/cron-email.sh`)
```
environments:
  master:
    cronjobs:
     - name: drush cron
       schedule: "H * * * *" # this will run the cron once per Hour
       command: /app/cron-email.sh
       service: cli
```

### Redeploy
Redeploy the environment(s) to make the change

### Notes
You could change the variables to lagoon runtime variables https://lagoon.readthedocs.io/en/latest/using_lagoon/environment_variables/ rather than defining in the script

**Comment by shreddedbacon** [comment]
Will work on a PR to add script to helpers and update documentation.

**Comment by fago** [comment]
This looks great! I'll get it a try and let you know how it works out.

**Comment by fago** [comment]
thx, this is working great! @shreddedbacon 

I've slightly improved the script:

```
#!/bin/bash

TO_ADDR=${CRON_NOTIFY_TO_ADDR:-"your-defaults-there"}
FROM_ADDR=${CRON_NOTIFY_FROM_ADDR:-"NOREPLY <noreply@example.com>"}

ERRFILE=$(mktemp)
SUBJECT="drush cron failure at $LAGOON_SAFE_PROJECT $LAGOON_GIT_BRANCH"
COMMAND="drush cron"

if ($COMMAND 2> >(tee $ERRFILE)) ; then
  echo "Cron exited clean"
else
  echo "Cron failed, sending email"
  ERROR=$(<$ERRFILE)
  sendmail $TO_ADDR <<EOF
To: $TO_ADDR
Subject: $SUBJECT
From: $FROM_ADDR

Command $COMMAND failed at $LAGOON_SAFE_PROJECT $LAGOON_GIT_BRANCH.
The error was:
$ERROR
EOF
rm $ERRFILE
fi

```

**Comment by shreddedbacon** [comment]
Thanks for the feedback @fago, glad its working for you. Changes look good, I'll work these into some documentation.

**Comment by tnelson-doghouse** [comment]
Is there any chance we could get the script placed somewhere inside amazeeio/php:7.3-cli-drupal (and other appropriate containers)?

**Comment by tnelson-doghouse** [comment]
Also, this would be simpler if you installed the "mail" program (mailx, s-nail, or something equivalent); it would do a fair bit of the lifting here; you could do things like:

drush cron | mail -s "Subject" 'example@example.com'

**Comment by fjgarlin** [comment]
Could we use the notification system used for the project? If we have Slack or Rocketchat notifications for the project, it'd be great that these notifications would go there by default too, with kind of zero set up or just an env variable to enable these notifications.

**Comment by tobybellwood** [comment]
As the solution may differ between lagoon implementations, closing here.

If we get a notification overhaul, we may consider a task/cron hook.
