### ISSUE TITLE
Add a new project should default the tasks to the correct type (OpenShift vs K8s)

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1695]
**Describe the bug**

At the moment when you add a new project to Lagoon (e.g. via the API), there are a few items in the `project` table in `api-db` that need to be manually changed

* `active_systems_deploy`
* `active_systems_remove`
* `active_systems_task`

Failure to change these for native kubernetes based projects will lead to things not working as expected when you deploy.

**To Reproduce**

1. Create a new project, create it on a native k8s cluster
2. Deploy
3. It will fail

**Expected behavior**

Lagoon is able to tell if a cluster is OpenShift or native k8s, and apply sensible defaults.

**Comment by Schnitzel** [comment]
currently lagoon does not do any validation of the openshift object data you send it to it (does the token work? does it have the right permissions, etc.).

The idea is though that in the future (version 2.0 of Lagoon) we abandon `active_systems_*` as we will also be able to use all the kubernetes services to deploy against an OpenShift Cluster. The only need for `active_systems_*` will be to still tell Lagoon to use the old openshift services for non-migrated namespaces (namespaces that are still deployed on an OpenShift cluster which have been deployed once with the openshift services).

because of this I don't think I would add any logic into lagoon to automatically have defaults for `active_systems_*` as they will go away anyway. 

I think for the time being we just need to document a bit better what is different when adding a project that should deploy against a kubernetes cluster.

**Comment by tobybellwood** [comment]
Lagoon doesn't support Openshift (3) any more, so this is no longer an issue
