### ISSUE TITLE
add logs2rocketchat

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#17]
Title says it all, like we have logs2slack today, we would need logs2rocketchat.
Maybe rocketchat ist slack API compatible, then we could actually use logs2slack for it.

I think @twardnw did some research here already?

**Comment by twardnw** [comment]
I did do some research, rocketchat implements their API as slack-compatible, so it will accept the current messages with no changes. I'll look to see if there is any additional features we can add on rocketchat vs. slack, otherwise we should just use the existing slack implementation, and not duplicate it to another file w/ just name changes.

**Comment by twardnw** [comment]
using a RocketChat webhook URL as a logs2slack endpoint does work, but has some formatting issues. Will continue with creating a separate service for RocketChat

**Comment by twardnw** [comment]
@Schnitzel , I thought I added the new functions correctly, but when trying to add a rocketchat notification to the API, graphql presents this error:
```
{
  "errors": [
    {
      "message": "dao.addNotificationRocketChat is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addNotificationRocketChat"
      ]
    }
  ],
  "data": {
    "addNotificationRocketChat": null
  }
}
```
Can you take a look when you have time?

**Comment by twardnw** [comment]
Thanks for the 🦆
