### ISSUE TITLE
SSH fingerprints and key length in the Lagoon UI

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1717]
**Describe the feature**

I wish to see the SSH key fingerprint in the UI next to the keyname. Bonus points for the key length in bits.

**Expected behavior**

Seeing this data is a lot more useful in the UI.

```
$ ssh-keygen -l -E md5 -f ~/.ssh/id_rsa.pub
4096 MD5:cf:19:96:94:52:7c:33:98:10:60:31:33:96:a3:69:44 iwiifm@gmail.com (RSA)
```

**Prior art**

This is what Github does

![image](https://user-images.githubusercontent.com/10605846/76563197-d02ee000-650b-11ea-95bd-e49347c1e028.png)

**Comment by dan2k3k4** [comment]
Github uses the new way to output:
![github-ssh-key-manage](https://user-images.githubusercontent.com/158704/104973590-6c135d00-59f5-11eb-9154-5333b235554d.png)

It looks like this was already fixed in #2125, as currently we have:
![lagoon-admin-ui-ssh-key-manage](https://user-images.githubusercontent.com/158704/104973658-a41aa000-59f5-11eb-9179-2629240cf21f.png)

For information, we currently use the [sshpk](https://www.npmjs.com/package/sshpk) node package.

**Comment by smlx** [comment]
@seanhamlin can this be closed?

**Comment by seanhamlin** [comment]
Sure can, thanks!
