### ISSUE TITLE
Get ready for Drupal 9

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1788]
Drupal 9 is coming and we should make sure we're ready for it, some tasks that come to my mind

- [x] add lagoonize files for Drupal 9
- [x] create a test that uses Drupal 9
- [x] fix all the issues that might arise from Drupal 9
- [x] update the documentation with Drupal 9
- [x] provide compatible MariaDB version - fixed in #1866 
- [x] write Lagoon tests for D9

**Comment by stewest** [comment]
FYI: When I try to install Drupal 9.0.0-beta 2 with composer create-project drupal/recommended-project:9.0.0-beta2 FOLDERNAME, I halt at the DB Install.

> The database server version 10.2.31-MariaDB is less than the minimum required version 10.3.7.

**Comment by stewest** [comment]
Also, Required PHP >=7.3

**Comment by dan2k3k4** [comment]
@stewest PHP 7.3 / 7.4 are already available on Docker Hub: https://hub.docker.com/r/amazeeio/php/tags
If your setup does not use 7.3+, then you may need to tweak your `php.dockerfile` such as: `FROM amazeeio/php:7.2-fpm` to be `FROM amazeeio/php:7.4-fpm`

@Schnitzel correct me if I'm wrong, I try to understand the complexity of upgrading MariaDB...

As for MariaDB, since Lagoon is setup to use a "Database as a Service" approach, (at least on the `OpenShift` infrastructure). This allows Lagoon to autoscale the DB from a single database instance to a Galera cluster.

I believe it also means that the database is using a shared service inside Kubernetes, per cluster, so this may mean that it would require a database upgrade for all the projects on that cluster (e.g. all projects hosted on ZH1 would need the MariaDB service to be upgraded, and then each project would then need to have their containers rebuilt to pickup on the new version).

I'm not sure if there are any breaking changes between MariaDB 10.2 and 10.3.

However, if you want to just play around with things locally, you would need to write your `Dockerfile` for the `mariadb` service.

The base [MariaDB Dockerfile](https://github.com/amazeeio/lagoon/blob/master/images/mariadb/Dockerfile) does not state that it uses a set version, so then we may only need to build a `Dockerfile` which uses the `mariadb-drupal` image and then runs APK get for the latest mariadb version.

Perhaps something like this:

Inside `lagoon/mariadb.dockerfile`
```Dockerfile
FROM amazeeio/mariadb-drupal

RUN \
    apk add --no-cache --virtual mariadb

```

Although looking at the base `amazeeio/mariadb` image, there are other commands being run after MariaDB is installed so we may have to [run those too](https://github.com/amazeeio/lagoon/blob/master/images/mariadb/Dockerfile#L49-L76).

Then update the `docker-compose.yml` file
```diff

-    image: amazeeio/mariadb-drupal
+    build:
+      context: .
+      dockerfile: lagoon/mariadb.dockerfile
```

And rebuild your project, then to verify if MariaDB is updated:
`docker-compose exec mariadb bash` and then `mysql --version`

**Comment by tobybellwood** [comment]
It'd need a change in the Alpine version on the dockerfile to get a higher version of mariadb than 10.2 - I think this is being worked on in a different ticket (#892), but had some galera issues

**Comment by stewest** [comment]
Yay thanks!
