### ISSUE TITLE
Unable to deploy a project if a container is unavailable for a pre-rollout task

### ISSUE THREAD

**Issue by steveworley** [uselagoon/lagoon#1804]
**Describe the bug**
It is possible to have an image build and then that image be unable to start (eg. a crash loop, due to runtime permissions). Further deployments will be blocked if the project is using a pre-rollout task that is expecting to be executed in the container that is in a crash loop.

```
+++ oc -n test-master exec cli-47-rw5hp -i -- bash -c 'mkdir -p /app/web/sites/default/files/private/backups'
--
  | error: unable to upgrade connection: container not found ("cli")
```

**To Reproduce**
1. Deploy a container that enters into a crash loop when running in OS
2. Define a pre-rollout task that uses the container that is crashing

**Expected behavior**
Lagoon should check that the container exists before running the pre-rollout task

**Comment by smlx** [comment]
>  Lagoon should check that the container exists before running the pre-rollout task

I wonder what the logic should be in that case? How can the build continue if the pre-rollout task fails?

**Comment by cdchris12** [comment]
This will be resolved by the updates in #1802

**Comment by shreddedbacon** [comment]
> This will be resolved by the updates in #1802

Maybe not entirely. This condition is a bit different to what that PR tries to solve.

**Comment by shreddedbacon** [comment]
> > Lagoon should check that the container exists before running the pre-rollout task
> 
> I wonder what the logic should be in that case? How can the build continue if the pre-rollout task fails?

~`pre-rollout` tasks will currently fail on initial deployments too. Which means someone trying to deploy an initial build will need to comment out their task, run a deploy, then uncomment it for subsequent builds.~
I like the idea of having this as configurable in the API rather than having to make people do a full git process just to enable/disable pre-rollout tasks.

If someone wants to temporarily disable a `pre-rollout` task, then maybe we need a `LAGOON_PREROLLOUT_DISABLED` envvar check? So an owner/maintainer can just add that to the API and trigger a deployment manually. Then when they're over the hurdle, they can remove it or set it to something else?

**Comment by tobybellwood** [comment]
The use case here also coverts the issue that a pre-rollout task can't, by definition, rely on something contained for the first time in the image being deployed, i.e. calling a script - so temp disabling via a build-time var would be perfect
