### ISSUE TITLE
Lagoon SSH Host Key changes

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1876]
**Describe the bug**
SSH HostKey warning when connecting to Lagoon via SSH.

**To Reproduce**
1. Connect to Lagoon via SSH.
2. Wait a week.
3. Connect to Lagoon via SSH.

**Expected behavior**
The HostKey should not change.

**Screenshots**
![Screenshot from 2020-05-13 17-56-50](https://user-images.githubusercontent.com/861778/81798917-2982b200-9543-11ea-8bda-9a0e7f598089.png)

**Additional context**
n/a

**Comment by Schnitzel** [comment]
the problem is that during the building of the SSH image, ssh is installed and it auto generates new SSH Host keys:
https://github.com/amazeeio/lagoon/blob/master/services/ssh/Dockerfile#L31

in order to fix this we would somehow find a way to mount the ssh keys from a persistent volume (shouldn't be too hard), but if that persistent volume is empty (which it will be during the very first start of the ssh container) ssh needs to create another set of host keys (probably with an entrypoint in the ssh container)

**Comment by smlx** [comment]
could we use a `Secret` instead of a persistent volume for the key?

**Comment by smlx** [comment]
This is not actually fixed until https://github.com/uselagoon/lagoon-charts/pull/382 is rolled out.

**Comment by tobybellwood** [comment]
Fix is in place, awaiting rollout of SSH portal
