### ISSUE TITLE
Openshift namespace labels aren't applied

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1969]
**Describe the bug**
Namespaces in OpenShift aren't labelled with the `lagoon.sh/...` labels on project creation.

**To Reproduce**
1. Deploy a project in OpenShift.
2. Inspect the namespace via the k8s API.
3. Observe no `lagoon.sh/...` labels.

**Expected behavior**
`lagoon.sh/...` labels should be added to the namespace.

**Screenshots**
n/a

**Additional context**
Labels on OpenShift namespaces were added in https://github.com/amazeeio/lagoon/pull/1917, but it seems that OpenShift [doesn't support labels on `ProjectRequest` objects](https://github.com/openshift/origin/issues/3819). Instead we will probably have to do this in two steps:
1. Create the project.
2. Patch the namespace.

These labels are important to the Lagoon logging system since they are used to determine project name / type.

**Comment by shreddedbacon** [comment]
It might also be worth discussing if we actually need to use the `Kind: ProjectRequest` to create the project. My understanding of the ProjectRequest is that it offers a way for developer accounts to create projects without giving them more permissions https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/cluster_administration/admin-guide-managing-projects
Since most of our operations are performed by cluster admin accounts, we could just create the openshift project directly and benefit from labels at the creation step
https://www.diffchecker.com/um8sPEwo

**Comment by seanhamlin** [comment]
This is preventing object syncers that rely on the labels to sync across objects like HPAs etc. This is hugely disruptive.

**Comment by smlx** [comment]
Just noting that there's a hacky workaround here: https://github.com/amazeeio/lagoon/blob/master/helpers/label-namespaces.sh

**Comment by tobybellwood** [comment]
Lagoon doesn't support Openshift (3) any more
