### ISSUE TITLE
Ingress can contain invalid TLS specification

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2310]
# Describe the bug

If one of the auto-generated domains is longer than 63 characters you can get an error from `cert-manager` and the certificate is not generated.

## To Reproduce

1. Create a project / environment combination with names long enough to hit the 63 character limit.
2. Deploy into Kubernetes.
3. ACME certificates aren't generated, and this event is seen:

```
21m         Warning   Failed              certificate/nginx-tls                         The certificate request has failed to complete and will be retried: Failed to wait for order resource "nginx-tls-j9v2s-618972317" to become ready: order is in "errored" state: Failed to finalize Order: 400 urn:ietf:params:acme:error:badCSR: Error finalizing order :: CSR doesn't contain a SAN short enough to fit in CN
```

## Expected behavior

I expected to get a valid certificate on my auto-generated route.

## Screenshots

n/a

## Additional context

I've tested this workaround and it does work https://github.com/jetstack/cert-manager/issues/1462#issuecomment-472416825

So probably the solution is to truncate the auto-generated domain if it is too long and prefix it to the list of TLS domains in the ingress.

**Comment by smlx** [comment]
Note to future self: we'll need to add a `CLUSTER_URL` in `services/kubernetesbuilddeploy/src/index.ts` in addition to `ROUTER_URL`, since `ROUTER_URL` already contains the environment and project.

**Comment by smlx** [comment]
Relatedly it appears Lagoon can also create invalid openshift routes for the same reason - names over 63 chars in `spec.host`.

**Comment by seanhamlin** [comment]
Just encountered this on Native Kubernetes, the `CN` was 66 characters log, and the error was

```
Failed to finalize Order: 400 urn:ietf:params:acme:error:badCSR: Error finalizing order :: CSR doesn't contain a SAN short enough to fit in CN
```

Adding another (made up) domain to the `ingress` object that was shorter fixed all the things and allowed the certificate to be created.

The ideal solution IMO here is for Lagoon to recognise that the domain is > 63 characters long, and if so, truncate/hash/pick letters from the project and branch names to make it shorter

Instead of

```
nginx-php.production.really-long-project-name.really.long.suffix.here
```

Use

```
nginx-php.production.rlpn.really.long.suffix.here
```

Or even, because this `CN` will never be used, just hash the first few labels, and use that, this is `sha256` and taking the first 8 characters of it.

```
ab60751b.really.long.suffix.here
```

Actually, the more I think about it, we could generate the hash 100% of the time for the `CN`, this way the logic might be simpler?
