### ISSUE TITLE
API does not return `baseBranchName`, `headBranchName`, or `number` for pull request environments

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2344]
These two fields are required to deploy a PR environment, but are not available via any of the environment related queries to the API. This makes it impossible to migrate a PR environment from one cluster to another

**Comment by rocketeerbkw** [comment]
The API stores environment deployment data normalized to account for all deployment methods (branch, promote, PR). This results in [four fields on the environment](https://github.com/amazeeio/lagoon/blob/main/services/api/src/typeDefs.js#L549-L564): `deployType`, `deployBaseRef`, `deployHeadRef`, and `deployTitle`.

Whenever a webhook or API deployment requests comes in, the data for these fields is [normalized and saved](https://github.com/amazeeio/lagoon/blob/main/node-packages/commons/src/tasks.ts#L348-L352). This allows the API to run the `deployEnvironmentLatest` mutation, where it converts the normalized data back into all the fields needed for whatever deployment is being run. For PRs, you can [map the data](https://github.com/amazeeio/lagoon/blob/main/services/api/src/resources/deployment/resolvers.ts#L436-L446) in the same way the API does.

That the API doesn't return `baseBranchName` or `headBranchName` is by design, and I don't think a bug.

**Comment by twardnw** [comment]
Those are easy enough to work around, but I did also just notice that `number` is also required by the API to create a PR environment deploy. For an existing project (aka migration) it would be possible to work this out via a regex.
