### ISSUE TITLE
Deploy hangs when container registry fails.  

### ISSUE THREAD

**Issue by tnelson-doghouse** [uselagoon/lagoon#2377]
# Describe the bug

1. We get the following error messages in our deploy
2020-12-04T00:42:48.306229219Z WARNING! Using --password via the CLI is insecure. Use --password-stdin.
2020-12-04T00:42:49.971050129Z Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

2. At that point, it hangs indefinitely.  We had one build run for 220 hours.  

(as a side note, should probably pipe in the password if you can).  

## To Reproduce

1. Create a Lagoon project
2. Enter bad credentials
3. Run a deploy

## Expected behavior

I expect this to cause a complete build failure.

**Comment by shreddedbacon** [comment]
Hi @tnelson-doghouse, I've looked into this issue and have found the problem. 

The build does exit correctly, but due to a queue issue in Lagoon after the recent release, the UI had shown that the build was running, even though the build had failed. This meant that the running timer kept incrementing as the UI had no idea what state the build was at. The one referenced running for 220 hours is actually related to #2046 and will be resolved once we move to using the build deploy controllers.

I'm going to mark this as closed as there isn't an actual issue with the build pod exiting, but a queueing issue that will be resolved once we make the move to the controllers. It is somewhat related to #1040

Also noted about the pipe to stdin for the password, we can definitely look into this, I'll raise that as a separate issue.
