### ISSUE TITLE
Harbor V2 API not compatible with Problems Webhook configuration

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#2576]
There's a number of minor changes in the Harbor v2.0 API that break our integration with the webhooks to retrieve problems.

It shouldn't require much effort.  From what I've found so far:

* `scanningCompleted` has become `SCANNING_COMPLETED` (and likewise failed) when setting up a webhook policy or receiving a webhook
* the endpoint to retrieve a scan has changed from a `/repositories` starting URL to requiring project and repository
* the scan endpoint itself has moved from `/tags/latest/scan` to `/artifacts/latest/additions/vulnerabilities`

I'll have a deeper look tomorrow.  The main question is, do we intend to support Harbor <2.0 in Lagoon 2.0 (i.e. do we have to build backwards compatibility into the Harbor sections of the API)

**Comment by bomoko** [comment]
@tobybellwood from the problems webhook perspective, supporting both should be fairly trivial, since _almost_ everything we need to change is localized in a single place - namely, https://github.com/amazeeio/lagoon/blob/main/services/webhooks2tasks/src/handlers/problems/harborScanningCompleted.ts
If all the incoming scan data is transformed at this point, regardless of where that data comes from, we can transform it into the right structure for downstream processing.

Are we still planning on supporting multiple Harbor registries? If so, then it feels like supporting multiple Harbor versions might be even more important.

**Comment by tobybellwood** [comment]
The API already has the ability to specify a Harbor API Version (via a variable) - so maybe we can use that for now and cover both?

**Comment by bomoko** [comment]
@tobybellwood - I think we can close this?

We need to rework the harbor integration completely either way.
