### ISSUE TITLE
Consider returning deployment details from `deploy` mutations

### ISSUE THREAD

**Issue by KorvinSzanto** [uselagoon/lagoon#2652]
There are currently 4 separate mutations to trigger an actual deployment with the lagoon api:
- `deployEnvironmentPullrequest: String`
- `deployEnvironmentBranch: String`
- `deployEnvironmentLatest: String`
- `deployEnvironmentPromote: String`

There's also `addDeployment: Deployment` but it doesn't work the same way as these others, it just adds the deployment record without triggering the action (maybe this is an issue with my environment?) so we will ignore it for now.

On success these 4 mutations all return the string "success", so there's no real way to determine _which_ deployment has been added by your mutation, only that _a_ deployment has been added. It's possible to hook into the broker to see status changes and assume which one is which but there's no real guarantee the deploy you see in the queue is the same one you triggered through a mutation. 

There are three ways I can see to make it possible to track this:

- Change the output to be a Deployment type instead of "success".
- Change the output to be generic but include a deployment ID or name.
- Allow the passthrough of some sort of state. EG let me pass something like `deploymentReferenceId` when creating the deployment and query it later (or see it as part of the broker update queue)

It's likely the third one would be the only one that'd maintain backward compatibility for what that's worth.

**Comment by rocketeerbkw** [comment]
You're correct that `addDeployment` doesn't trigger a deployment, it's just a database insert.

The first two options, returning any kind of deployment data, is not just a BC break it's not currently possible for architecture reasons (see below).

With Lagoon 2 we have control over the entire deployment, so it could be possible to add some passthrough data, we just need to be able to store it in the Lagoon api and the kubernetes deployment(?) resource.

Some background on why we can't currently return deployment info for anyone who works on this issue:

It used to be the only way you could trigger a deployment was to commit and push which would trigger a webhook from github OR to use a separate REST api. In #838 we copied all the REST endpoints into graphql so that we could deploy from the new Lagoon UI. In order to not break too badly external code that was using the REST api we did a straight copy of the interface and used the same underlying system of deployments. The methods works by creating a task (internal task, not a lagoon environment task) in a rabbitmq which eventually would get picked up by the deployment system at which point it would add all the relevant info to the api (via `addDeployment`). The other major blocker is that openshift used to control the deployment system, so we had no info on what the deployment data would be until openshift actually started the deployment.

With Lagoon 2 we use an entirely different deployment workflow and I think it would be possible for us to invert the process and add a deployment to the api first, then have it get picked up by the deployment system. This would requrie a BC break and some bigger under-the-hood changes.

**Comment by tobybellwood** [comment]
FYI - we're currently working on an additional :scream: kind of deployment (bulk triggered) - that will define the ID on the trigger and pass it to the deployment, which can then follow the deployment through the process - we should be able to roll this out to more deployment types to allow for easier retrieval.
