### ISSUE TITLE
allow seperator in autogenerated routes to be configureable

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2666]
In our charts it is currently assumed that a service name will be prepended to the router pattern with a `.`. This should be configurable to allow administrators the option to choose a different DNS-safe seperator, such as `-`. The build-deploy script should also check that the length of FQDNs generated using a customized seperator are also DNS-safe.

**Comment by smlx** [comment]
I think this is a duplicate of https://github.com/amazeeio/lagoon/issues/2573

**Comment by twardnw** [comment]
@tobybellwood , would it be possible to have this assigned in the near future? I have a customer where we've hacked a fix for this and they are operating from an out-of-date fork, but are now seeing issues around the length of FQDNs being generated with the customized seperator. I'd like to not have to fix that with another hack of their build-deploy script :D

**Comment by Schnitzel** [comment]
so in my understanding this is what we would need to do:

Currently the creation of the autogenerated ingress host happens on two places:
in the lagoon api you can define on the openshift or project object the router pattern which looks something like: `${environment}.${project}.test1.amazee.io`

1. to generate the environment and project host happens inside lagoon kbd:
https://github.com/amazeeio/lagoon-kbd/blob/e23cf2a8df46a221677196d3b873bd188332e688/controllers/lagoonbuild_helpers.go#L515-L530

2. then inside the helmcharts for each service we are adding the prefix for the service:
https://github.com/uselagoon/lagoon/blob/ea9ccc17a685f8404eab030ebfd50015136a24f0/images/kubectl-build-deploy-dind/helmcharts/nginx/templates/_helpers.tpl#L27-L33

this the end we would like to be able to add the servicename into the routerpatttern, so we could define something like:
`${service}.${environment}.${project}.test1.amazee.io` or for customers that don't like to generate subdomains per service and environment: `${service}-${environment}-${project}.test1.amazee.io`

so my suggestion would be:

- remove the replacement of environment and projectvariables from lagoon-kbd
- do the replacement of `service` `environment` and `project` in helmchart
- make the replacement clever enough to automatically add the servicename as a prefix if it's not defined in the `routerPattern` (to keep backwards compatilibity). <-- could also happen on lagoon-kbd level so that helmcharts always can expect a router pattern with `${service}` and to keep the complexity inside the `_helpers.tpl` low.

**Comment by twardnw** [comment]
One part of this that caught a customer recently is to ensure that when the separator is _not_ a `.` to shorten the string to a DNS safe length

**Comment by Schnitzel** [comment]
discussed in lagoon tech meeting:
- remove logic from kbd
- add replacement logic (service, environment, project) to helmcharts 
- add lagoon core upgrade script that adds `${service}.` to all routerPatterns
- add validator to `routerPattern` in lagoon core api that checks that the routerPattern has `${service}` `${environment}` `${project}` defined in it
- update documentation
