### ISSUE TITLE
StorageCalc should not run on RWO PVs that are already mounted

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2789]
# Describe the bug

I occasionally see storagecalc pods for PVs that are ReadWriteOnce (RWO). StorageCalc attempts to mount the PV in order to do the `du` but fail to get the claim.

![image](https://user-images.githubusercontent.com/10605846/127395906-84b1dec3-b05b-4c5b-ace8-715b683d6fe3.png)

## To Reproduce

1. Create RWO PV, e.g. Solr
2. Wait for storageCalc to run (daily)
3. See error above

## Expected behavior

Just skip over RWO PVs that are mounted.

**Comment by vincenzodnp** [comment]
I saw the same issue and I was prepping a PR by setting an `interpod-affinity` rule and be sure `storagecalc` pod is scheduled in the same node where `solr` pod is.
The idea is to modify the helmchart and add something like 
```
podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
```
I'd use `preferredDuringSchedulingIgnoredDuringExecution` instead of `requiredDuringSchedulingIgnoredDuringExecution` because `storagecalc` must run even if  any Solr pod scheduled 

@seanhamlin

**Comment by tobybellwood** [comment]
new storagecalc fixed this
