### ISSUE TITLE
Create custom graphQL directives

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#2880]
following on from #2877 we should consider creating custom directives (https://www.apollographql.com/docs/apollo-server/schema/creating-directives/)

These could be to cover:
- Experimental features (such as DeployTargets)
- UI (or CLI) -specific features

**Comment by rocketeerbkw** [comment]
If the directives are exclusively for documentation purposes, our custom directives won't be surfaced by any tools. Since `@deprecated` is part of the spec it's treated differently. The only way someone would see our custom directive is if the looked at the `typeDefs.js` itself.

Here's a quick example of a custom `@alpha` directive (not being) shown in Insomnia.ap
<img width="990" alt="Fullscreen_10_19_21__6_48_PM" src="https://user-images.githubusercontent.com/92499/138005725-6bb6e490-c901-4fdd-b0c3-be57c610087a.png">
p

**Comment by tobybellwood** [comment]
ugh, so close...
