### ISSUE TITLE
Do not send notifications for pushes which do not lead to deployments

### ISSUE THREAD

**Issue by Leksat** [uselagoon/lagoon#2970]
Some time ago, webhook notifications were sent out only for branches which had enabled environments. Later it was changed. Currently notifications are sent for any pushes.

<img width="728" alt="Screen_Shot_2021-12-16_at_15_11_22" src="https://user-images.githubusercontent.com/989015/146765783-a9d8d541-54e1-4da7-acb9-06bbd3cf9e0c.png">

In my case, this does not add any profit, but only increases the noise in the notification channels. But I can imagine it can be a desired behavior for someone. So maybe it could be implemented as an option to enable/disable notifications for "no-environment" pushes?

**Comment by jrsouth** [comment]
This is happening to us too, and is particularly noisy when we have several projects running off the same repo. 

Whenever a developer pushes to their working branch ― early and often! ― it triggers 5 notifications in the channel. (And because that channel contains important messages it's set to override any do-not-disturb settings, including mobile notifications.)

**Comment by shreddedbacon** [comment]
I'm just reviewing this. Currently our notifications don't have the ability to be selectable on what is sent via the notifications system.

But the reason these messages are being sent is actually a bug, I'm working on a fix for this which should hopefully be in the next release, but will see if we can possibly hotfix prior to help reduce noise.
