### ISSUE TITLE
Move the Database migrations away from Mysql/Mariadb specific implementation

### ISSUE THREAD

**Issue by bomoko** [uselagoon/lagoon#2995]
Currently, altering the database schema is done via a set [of Mysql/Mariadb stored proceedures](https://github.com/uselagoon/lagoon/blob/main/services/api-db/docker-entrypoint-initdb.d/01-migrations.sql) that act as a migration system.

In an effort to (1) make the API database more DB neutral and (2) provide a better developer experience for contributors, it would be good to introduce a migration management tool (eg. [golang-migrate](https://github.com/golang-migrate/migrate))

**Comment by rocketeerbkw** [comment]
Also to (3) allow api-db to run in a sql-as-a-service like amazon RDS instead of as it's own image.

These are the tools I've looked into briefly:

[knex.js](https://knexjs.org/#Migrations)
- Pros
  - Support PostgreSQL, CockroachDB, MSSQL, MySQL, MariaDB, SQLite3, Better-SQLite3, Oracle, and Amazon Redshift
  - We're already using the library as a query builder
  - The schema builder can be used to write db-agnostic migration queries
  - Probably the quickest to start using right away?
- Cons
  - Still requires writing migrations manually

[Prisma.io](https://www.prisma.io/migrate)
- Pros
  - Looks like a stand-alone tool that we could implement w/o also implementing their SQL client
  - Migrations are automatically generated from schema file changes, and can be customized as needed
  - The Prisma client can use the same schema files to auto generate a Typescript ORM which actually looks really nice and I'm interested in researching further
- Cons
  - It's [less than a year old](https://www.prisma.io/blog/prisma-migrate-ga-b5eno5g08d0b)
  - [Fewer supported databases](https://www.prisma.io/docs/concepts/components/prisma-migrate/supported-types-and-db-features): PostgreSQL, MySQL, MSSQL, SQLite
  - The actual migrations, once generated, appear to be db-specific. That may complicate/preclude being able to run them against mariadb in prod and sqlite in test.

[umzug](https://github.com/sequelize/umzug) and [db-migrate](https://github.com/db-migrate/node-db-migrate)
- Older, more mentions in google/blogs
- Looks like the same architecture as knex, just using different schema builders?

edit: Forgot to add, I was primarily looking at node.js solutions since that is what the api is written in, and where I see this kind of tool living. Makes it easier for contributors if it's all the same language. I'm not inherently opposed to other languages though if they have a compelling difference.

**Comment by bomoko** [comment]
@rocketeerbkw - very nice.

I actually like the idea of running the migrations using knex, given that it gives us some unity across the api. As you point out, though, it's not a stand alone tool. I don't think that's a big deal though.

I also don't think it's too much of an issue that one needs to write migrations rather than have them generated from a schema - especially given something like knex's syntax is so straightforward.

**Comment by smlx** [comment]
Another big advantage of doing this will be to make migrations up and down unit testable against the supported backend DBs.

**Comment by tobybellwood** [comment]
Decision to run with knex migrations inside the API container, using locking to ensure multiple containers don't migrate at the same time. Logic to be  added to determine whether migrations are required (and add option to be run regardless)

**Comment by tobybellwood** [comment]
Done for now - still pretty mysql-centric, but definitely not stored procedures
