### ISSUE TITLE
XDebug doesn't work anymore and drush blocks as long as the PHPStorm debug listener is enabled

### ISSUE THREAD

**Issue by twerthmueller** [uselagoon/lagoon#396]
After updating to the latest containers with `docker image ls --format "{{.Repository}}:{{.Tag}}" | grep amazeeio/ | grep -v none | xargs -n1 docker pull | cat` XDebug does not work anymore and as long we have enabled the debug listener in PHPStorm, Drush does not work and is blocked when we execute a command.

As soon as we stop the debug listener in PHPStorm, Drush works again. Drush and XDebug still works on lagoon projects with previous built containers, but as soon as we rebuild the containers, we have the same problem.

What I currently not understand is the behave of Drush, because Drush seems to trigger XDebug and is waiting of a response.

I discussed this also with @dasrecht but we didn't find a solution, that XDebug works again with the newest containers.

**Comment by Schnitzel** [comment]
> Drush does not work and is blocked when we execute a command.

that's actually expected? Or at least Drush is configured that if `XDEBUG_ENABLE` is set to `true` and it finds a port `9000` to connect to, it will try to connect to it, as it assumes that you want to use xdebug.
The weird thing is though why it stops? This sounds to me like PHPStorm blocking the request or waiting on some developer interaction within PHPStorm?

Let's discuss today in Slack and do a remote session, because on our test infrastructure xdebug works with PHPStorm.

**Comment by twerthmueller** [comment]
Yes we can do that. One thing I also see it's in the xdebug conf:

'xdebug.remote_host' was before the update 'docker.for.mac.localhost' and nor the IP '172.19.0.1'.

**Comment by Schnitzel** [comment]
will be handled with https://github.com/amazeeio/lagoon/pull/397
