### ISSUE TITLE
Donate and Maintain Drupal Images to https://github.com/drupal-docker

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#48]
During DrupalCon Vienna we had a BOF about Docker and Drupal, together with @zaporylie we discussed that it would make sense to combine efforts for preconfigured Drupal Images.

The idea would be that the Drupal Images that are built within Lagoon are donated to https://github.com/drupal-docker and maintained over there.

There are a couple of questions left:
1. https://github.com/drupal-docker has currently alpine and non-alpine images. At Lagoon we plan to run everything with Alpine. Is it fine to deprecate the non-alpine images?
2. How many other structural changes are allowed? For example there is https://github.com/drupal-docker/php/blob/master/7.1/Dockerfile-cli which is a cli container with drush, composer, etc. installed. Inside Lagoon this would be called a builder image, can we rename them?

**Comment by Schnitzel** [comment]
also pinging @skwashd as he is working on the new Lagoon Alpine Images

**Comment by zaporylie** [comment]
ad. 1 I believe it is ok to deprecate debian-based images and go for alpine. I would still wanna continue mysql/mariadb images maintenance though, as it makes much easier for non-ops to run Drupal projects locally, and these are not available in alpine-flavour :disappointed: 
ad. 2 With good communication and upgrade path documentation we can do all changes we want :smile:  However I would be sceptical about this particular change - IMO "cli" tells much more to the potential adaptor than "builder", as it can be used on the runtime for cli tasks (e.g. by developers to run containerized drush command). Please note that example you're referring to has composer installed but no global drush or drupal console. In Drupal we are trying to move away from global drush or console as much as we can, due to version incompatibility, dependency hell etc. You could still inherit drupaldocker/php:7.1-cli base image in one of amazee.io base images, add tools required by amazee toolchain (npm/yarn, drush, console) and publish under your vendor name. The goal here is to find common layer and publish it within https://github.com/drupal-docker and keep the rest for hosting vendors.

There are some additional changes that needs to be done:
- VOLUME instruction deprecation (to allow multi-stage builds)
- Add USER (and stop using root)

I like to think of https://github.com/drupal-docker as a community project and I believe it should stay this way. This is why I migrated it from my personal namespace to dedicated organisation at very early stage. Hence, at some point, we must discuss project's governance. I would love to have more people on the team, ideally one committer responsible for each component (i.e. php/nginx/apache/mariadb/mysql).  You folks have spent more time on Drupal Dockarization than I can probably imagine (and more I could ask for). It's fantastic to see that you've grown from single to multi-container applications in just a couple of months and now provide docker-on-production hosting. All of that gives me certain level of confidence in the quality of work you provide and I would definitely love to see you as a project's partner. Nevertheless we must make sure it's more of a cooperation ("adjustments allowed") than donation ("take as it is").

**Comment by Schnitzel** [comment]
> I would still wanna continue mysql/mariadb images maintenance though, as it makes much easier for non-ops to run Drupal projects locally, and these are not available in alpine-flavour 

our plan is actually to create mariadb alpine images :)

>  IMO "cli" tells much more to the potential adaptor than "builder", as it can be used on the runtime for cli tasks (e.g. by developers to run containerized drush command)

that's actually still my idea, have the same Image for building php things and use the same image also for cli. Guess it should be called build-cli then? :) 

> Please note that example you're referring to has composer installed but no global drush or drupal console. In Drupal we are trying to move away from global drush or console as much as we can, due to version incompatibility, dependency hell etc.

mhh good point, actually we never installed drupal console directly but only the launcher: https://github.com/hechoendrupal/drupal-console-launcher which will search for a console installed within the drupal project itsef. But still provides a nice `drupal` command.
The same for Drush, drush since quite some time has the launcher included, so if there is a drush installed in the current $PWD it will be used instead of the global drush. But you need the global drush installed for a nice `drush` command. (unless there is maybe a way to have a drush command without a global drush installed?).

> Hence, at some point, we must discuss project's governance. I would love to have more people on the team, ideally one committer responsible for each component (i.e. php/nginx/apache/mariadb/mysql).

Yes full agree, for example we probably never will have apache images in our repertoire (famous last words?), so if somebody wants to maintain apache drupal images that would be awesome.

 > Nevertheless we must make sure it's more of a cooperation ("adjustments allowed") than donation ("take as it is").

Yep, sorry maybe "donation" isn't the right word here to use, that's why I wrote "donate and maintain" instead of just maintain :)

So how should we continue from here? Should we just send you pull requests to the existing repos? Or should we create new repos with alpine only and "deprecate" the old repos with migration/upgrade paths?

**Comment by Schnitzel** [comment]
We think this is too complicated for now, closing
