### ISSUE TITLE
GitHub PR Builds: Ignore changes of Description

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#601]
When you change the title of a PR this triggers a new build in Lagoon, which is awesome as then the matching of the PR Title comes into place and people can enable a build of a PR which previously was not enabled.

But a simple change of the description of the PR also triggers another build, that causes way too many rebuilds for some clients.

We therefore should ignore updates to PRs that **only** include an update to the description.

here how this looks like:
https://gist.github.com/Schnitzel/3117d1dd65414ea005abda5dbc6fa78f#file-description-json-L337-L341
and here a change to a title:
https://gist.github.com/Schnitzel/3117d1dd65414ea005abda5dbc6fa78f#file-title-json-L337-L341

Important: there is the possibility that the title and the description could change at the same time, then we still would need to trigger a rebuild.

**Comment by zanettin** [comment]
just a question about this: can we relay on the `changes` key on your linked json files? since `title` and `description` never can update at the same time (github UI does currently not allow that as far as i know) we should be able to ignore all changes which just affect the `body`:

re-rolle:
```
"changes": {
    "title": {
      "from": "DTC-XXX reduce docker image size"
    }
  }
```

ignore:
```
"changes": {
    "body": {
      "from": "foo bar baz"
    }
  }
```
