### ISSUE TITLE
Pods won't wake up after pinging them

### ISSUE THREAD

**Issue by fjgarlin** [uselagoon/lagoon#647]
We've had several occasions where pods wouldn't wake up after visiting the URL several time for +20 minutes. Sometimes triggering an empty deployment fixes the issue, but this is not ideal and it's not always an option (ie: PM at client meeting). 

Is there anything that can be done to solve this without forcing the pods to be _always_ up?

**Comment by Schnitzel** [comment]
This is not specifically a Lagoon problem, but rather an OpenShift one and probably the issue lies in the specific cluster that your projects are running (amazee.io is aware of them and is working on resolving them). There is a possibility in Lagoon to disable the idling, so if you have an important @fjgarlin time coming up where the projects should not be idled, please ping support so they can change it.
