### ISSUE TITLE
NGINX building from openresty requires newer SSE4.2 compatible CPU 

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#649]
Just something I encountered - now that the NGINX images have switched from alpine to openresty, it has introduced a requirement for SSE4.2 compatible CPUs on the host machine (pretty much anything 2011-onwards - but you'll need to check) - some reference at https://github.com/openresty/docker-openresty#tips--pitfalls

It will manifest itself as the NGINX container building, but not deploying (immediate fail with a exit code 132.

Mounting the failed container and running nginx directly will result in an `illegal instruction` error.

Luckily Ebay is a good hunting ground for old brand-new CPUs...

**Comment by Schnitzel** [comment]
@tobybellwood 
wow nice found! Do you have cases where this affects local development?

I went down the rabbithole and researched that, looks like there is a performance loss if we run an OpenResty without SSE4.2 flags on a SSE4.2 compatible machine (but actually only for the LUA stuff, so not the nginx part of openresty).

There is though an Issue: https://github.com/openresty/docker-openresty/issues/39 and PR https://github.com/openresty/luajit2/pull/20 that will teach LUA how to decide to use SEE4.2 in runtime instead of buildtime.

Until then I think the easiest would be to run our own openresty version without SSE4.2 flags.

**Comment by tobybellwood** [comment]
I honestly think it's not worth the effort to re-engineer around a problem that no-one else has reported - if more people do, then we should pursue - I more left this here in case anyone else comes across it!

For the record, my brand-new 2013-era FX-8320 CPU does the job just fine now!

**Comment by rzr** [comment]
https://github.com/openresty/luajit2/pull/75 may help to support non SSE-4.2 CPU
