### ISSUE TITLE
Improvements for Tasks System

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#729]
- [x] Delete Jobs with the Payload of `{"kind":"DeleteOptions","apiVersion":"v1","propagationPolicy":"Foreground"}` this will cause Kubernetes to also delete the Pod, if we delete just the Job, the Pod is still existing and uses resources
- [x] make `addTask` parameters easier, currently we need this payload to create a task:
```
  addTask(input:{environment:14129, service: "cli", name: "hello", command:"echo 'hello'", status: ACTIVE, created:"2018-10-07 23:02:41"}) {
    id
  }
```
Let's remove the need for `created` and `status` in `addTask`
- [x] When creating the PodSpec for the Job, let's remove the env variable `CRONJOBS` from it, as this causes the Job Pod to also initialize the Cronjobs and this could lead to weird behavior

**Comment by rocketeerbkw** [comment]
@Schnitzel when testing with minishift, just deleting the job would delete all the related resources including pods. Do you know what would be different that I could test that locally?

**Comment by rocketeerbkw** [comment]
When testing locally again, I noticed that pods weren't automatically deleted. I guess I missed it last time or that's a change introduced in openshift 3.9? I implemented the `DeleteOptions` and pods are being delete locally now.

**Comment by HurricaneInteractive** [comment]
@Schnitzel & @rocketeerbkw are you guys able to add the ability to delete older tasks? or at least archive and remove them from the task view? I created an issue #987 which is caused by timeout requests and reducing the number of tasks being loaded at one time would help with the issue for a while.

**Edit**
OR, for the single task page at least, when the request times out, filter through the returned tasks in the error object and checking if the current task object was returned before displaying the error message.

**Comment by Schnitzel** [comment]
@HurricaneInteractive 
please don't comment on closed issues, there is currently https://github.com/amazeeio/lagoon/issues/961 and the one you opened https://github.com/amazeeio/lagoon/issues/987 as well. let's discuss there.
