### ISSUE TITLE
UI: Deployment overview very slow or sometimes times out when many deployments existing

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#742]
this is the querry we run:

```
query getEnvironment($openshiftProjectName: String!) {
  environmentByOpenshiftProjectName(openshiftProjectName: $openshiftProjectName) {
    id
    name
    created
    updated
    deployType
    environmentType
    routes
    openshiftProjectName
    project {
      name
      __typename
    }
    deployments {
      id
      name
      status
      created
      started
      remoteId
      completed
      buildLog
      __typename
    }
    __typename
  }
}
```
Problably remove the `buildLog` will make it faster

**Comment by Schnitzel** [comment]
after some research I see that we currently have no way to load a single deployment based on the name.

So I would suggest:
https://github.com/amazeeio/lagoon/blob/6db6628ecc7370ff5561be35be0ff2f9001838c4/services/ui/src/pages/deployments.js#L14-L41 is currently used for display of all deployments and a single deployment, change that to:
1. create two different graphql requests, one for the overview, one for the individual view
2. update the Lagoon API so that `deployments{}` of a project can receive a name

**Comment by rocketeerbkw** [comment]
I split up the components and added the deployment api filter as suggested, overall it feels cleaner.

However, after doing all that work, and assuming that the `buildLog` really is the cause of the slowness, I think it still wouldn't have fixed anything. That's because the way our resolvers are setup is to query all the data first, and then the graphql server filters out based on what the user wants. So even if you remove `buildLog` from the graphql query, we still would have to query elastic search for every deployment to include the build log in the resolver.

There were two ways to try to fix this: add paging to the deployments page, so only 5 or 10 build logs are loaded at a time; or try to avoid querying the build logs at all if not needed.

I went with option 2 and found an extra parameter for the resolver and a library to help get what fields the query is requesting: https://github.com/amazeeio/lagoon/pull/750/commits/b134938e70db25f1d693c99c633873eece042cba
