### ISSUE TITLE
UI: Sidebar not wide enough to display full email addresses

### ISSUE THREAD

**Issue by ChandeepKhosa** [uselagoon/lagoon#761]
**Describe the bug**
When on a project page, I can't see full email addresses.

**To Reproduce**
1. Go to 'https://ui-lagoon-master.ch.amazee.io/project?name=lead-2030'
2. See the email addresses are truncated

**Expected behaviour**
I expect to see the full email addresses.

**Screenshots**
Not good 
<img width="1679" alt="screenshot 2018-11-15 at 00 06 55" src="https://user-images.githubusercontent.com/705104/48521258-b3c55980-e86b-11e8-92d7-d0fabb4505c7.png">

Good, but with inline browser hack
<img width="1680" alt="screenshot 2018-11-15 at 00 07 09" src="https://user-images.githubusercontent.com/705104/48521271-be7fee80-e86b-11e8-8918-f57e05a1ee31.png">

**Additional context**
I am using my 15" MacBook Pro and the viewport is showing as 1680px wide

**Comment by fubarhouse** [comment]
I'd like to volunteer to complete this one.

Edit: never mind, I've got something in mind.

**Comment by fubarhouse** [comment]
I've got a version which will now float the two components - name and email.
It will also change the display property of the details pane to be inline-table so that in the event the name and email are _that_ excessive, the sidebar will adjust according to them. This is rather unlikely, but here's an example of the full set of changes:

![image](https://user-images.githubusercontent.com/3070264/48547791-8d60f600-e91f-11e8-96d3-7eb39bc8289a.png)

I'll get a PR in place.

**Comment by ChandeepKhosa** [comment]
Thanks, I think that is cool
