### ISSUE TITLE
Dashboard backup download button doesn't update

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#786]
When triggering a download of a backup from the lagoon dashboard, and noticed that after 'PREPARE DOWNLOAD' button switches to read 'PREPARING...', it appears not to update once the download is actually ready. 

I discovered this be accident after refreshing the page as I thought nothing was happening, and the button immediately updated to 'DOWNLOAD'.

This is pretty low-impact, but I ended up sitting around waiting for the button to update. If a user didn't know to refresh the page, they would not be able to download the backup.

**To Reproduce**
1. Go to the backups tab of an environment in the lagoon UI
2. Select 'PREPARE DOWNLOAD'
3. 'PREPARE DOWNLOAD' switches to 'PREPARING...'
4. Requires a page refresh to show 'DOWNLOAD' when backup is ready.

**Expected behavior**
Expected the button to switch to 'DOWNLOAD' when the download was ready rather than having to refresh the page.

**Comment by Schnitzel** [comment]
@rocketeerbkw 
is that something that could be implemented with GraphQL Subscriptions? I don't know tooo much about them but I think we will have more "autorefresh" parts of the UI in the future (like adding an environment when a new one is added, removing it, updating deployment statuses).
So spending some time on figuring out Subscriptions would probably be cool :)

**Comment by rocketeerbkw** [comment]
I've also been thinking about this since the deployments page was finished. I think subscriptions are the correct way to do updates. `apollo-client` supports them natively, which we are using. `apollo-server` also supports them, but we aren't using the full library. We need to implement the auth layer and filtering so users can't get data they don't have access to, but it looks like it's flexible enough to handle those cases.
