### ISSUE TITLE
Display the limit of environments

### ISSUE THREAD

**Issue by Leksat** [uselagoon/lagoon#876]
Current issues:
- Developers might not know about the limit of environments
- Currently there is no way to learn the limit (maybe via API? but still not so obvious)

Proposed solutions:
- Variant A: add the limit of environments to the Lagoon UI
- Variant B: add a (Slack) notification, like  
    > :warning: **[project]** PR [#123 (PR name)](#) opened in Company/project
    > ERROR: environment won't be created because the limit of environments is already reached.
- Variant C: A+B

**Comment by fubarhouse** [comment]
It would be ideal to have an indicator to show why a build may have failed to show up, opposed to investigating and telling people why. Why not both?

**Comment by Leksat** [comment]
Added Variant C :)

**Comment by kaypro4** [comment]
Just ran into this issue myself and would vote for variant C.

I'd suggest that B has some brief info on how to resolve the situation and get the PR or commit built since that would be the next question on my mind.

Something like: To resolve, remove unused environments and post an empty commit to your branch to deploy.

**Comment by rtprio** [comment]
Variant A is in the attached PR #914 

I'll create another PR for Variant B.
