### ISSUE TITLE
mutation deleteEnvironment{} does nothing...

### ISSUE THREAD

**Issue by fubarhouse** [uselagoon/lagoon#878]
**Describe the bug**
The `deleteEnvironment` mutation does nothing when tested locally and in OpenShift.

**To Reproduce**
Steps to reproduce the behavior either:
1. Build lagoon locally and run the following:
```
mutation {
  deleteEnvironment(input: {
    name: "Development"
    project: "high-cotton"
    execute: true
  })
}
```

or:

2. For the recommended path to completion, click the 'delete' button on one of the environments in the Lagoon UI, and wait a given time and/or refresh.

**Notes about reproducing**

The response returns successfully.

Note the following, because `project` is a `String`, and the following is invalid as a `String`:

![image](https://user-images.githubusercontent.com/3070264/52189965-15f09200-2890-11e9-9918-e0827c89dc28.png)

**Validation**
Running remotely, the environment just never is removed.

Locally, the behavior can be validated using:
`select name, project from environment where project = 18;`

Receiving this after running the graphql mutation:
````
MariaDB [infrastructure]> select name, project, deleted, updated from environment where project = 18;
+-------------+---------+---------------------+---------------------+
| name        | project | deleted             | updated             |
+-------------+---------+---------------------+---------------------+
| Master      |      18 | 0000-00-00 00:00:00 | 2019-02-04 03:11:27 |
| Staging     |      18 | 0000-00-00 00:00:00 | 2019-02-04 03:11:27 |
| Development |      18 | 0000-00-00 00:00:00 | 2019-02-04 03:11:27 |
| PR-175      |      18 | 0000-00-00 00:00:00 | 2019-02-04 03:11:27 |
+-------------+---------+---------------------+---------------------+
4 rows in set (0.00 sec)
````

Also note the following:
````
MariaDB [infrastructure]> select name, project, deleted, updated from environment where project = "high-cotton";
Empty set (0.00 sec)
````

**Expected behavior**
Expectation is to have the environment row to at least be updated with a timestamp or marked in some way as deleted. Locally it's understandable that the deleted flag isn't utilized (given the timestamps) however the functionality isn't there.

Ideally, it would be expected to remove the environment build from OpenShift.

**Screenshots**
n/a

**Additional context**
I'm happy to provide more detail.

I'm guessing `project` should be an `Int!` which should refer to the project ID which will trigger the query with results targetted, opposed to running a query against an empty response with no results.

**Comment by rocketeerbkw** [comment]
The inputs for `deleteEnvironment` haven't changed, just the functionality. So the project is still a string. Previously, this function would only update the `api-db` to mark the environment as deleted. Now, when `execute: true`, it will put a task in the lagoon system that will attempt to delete the environment in openshift. To avoid data consistency errors, the environment will only be marked as deleted in the api after lagoon has successfully deleted the environment in openshift. If there was some reason the environment could not be deleted, it would never be marked as deleted. When you set `execute: false` (and have an admin api token) you tell the api that you don't want to execute the delete task, you just want to mark it as deleted immediately.

Just attempting to delete one of the test environments that are created on first run is not likely to work because the openshfit information that `api-db` contains for the project is likely to be incorrect, and so the `openshiftremove` service will be unable to delete the environment. And even if it were correct, it's unlikely that you have a project/environment running in openshift that matches the data. If you watch the logs, you'll probably see errors from the `openshiftremove` service.

So a test that will work requires an environment that has been deployed to openshift already. One way to accomplish that is by [commenting out the "remove" part ](https://github.com/amazeeio/lagoon/blob/master/tests/tests/nginx/nginx.yaml#L49-L65)of the nginx tests and run `make tests/nginx`. After the test have run, you should be able to run a mutation and shortly later have the environment get deleted and marked as such:
```graphql
mutation {
  deleteEnvironment(input: {
    name: "nginx"
    project: "ci-nginx"
    execute: true
  })
}
```

**Comment by fubarhouse** [comment]
I have in fact tested this on our OpenShift instance and the results were identical. No change, no failure, only success and no change or removal follows. Using the 'delete' button in the individual branches was one of the ways I tested this and it continues to say 'queued for deletion' and that is all it does with no following action.

It was my expectation that an individual branch would be deleted from OpenShift and the api-db table would be updated. Not what I expected but there you have it. Feel free to close this one.

**Comment by fubarhouse** [comment]
Seems like it's working this morning, for whatever reason. I'll close this one.
