### ISSUE TITLE
Replace "oc process" with another templating engine

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#943]

**Comment by snpdev** [comment]
@Schnitzel, We first considered the use of Helm charts as a replacement for OpenShift templates. WIP in https://github.com/snp-technologies/lagoon/tree/helm-integration.

Regarding the known security vulnerability in a multi-tenant environment, where the Tiller pod is running globally (i.e. in the kube-system namespace), we know that [Helm can be run securely](http://technosophos.com/2017/11/20/securing-helm.html) where Tiller runs in each tenant namespace, however this adds overhead.
An alternative we can look into is:
- Continue conversion to Helm charts
- Use the `helm template` command to render each chart as a native Kubernetes manifest. See https://github.com/technosophos/helm-template
- Deploy the manifest via `kubectl apply`, rather than `helm install`, hence no need for Tiller.

How does this sound?

P.S. We understand that Tiller will be removed in Helm 3. I hear that a preview ETA for Helm 3 is Q2 2019.

**Comment by snpdev** [comment]
@Schnitzel, As discussed earlier today, @siva2krish will proceed with a PoC of the `helm template` option. We'll aim to commit to https://github.com/snp-technologies/lagoon/tree/helm-integration by the end of the week.

**Comment by Schnitzel** [comment]
@snpdev perfect, sounds awesome :)

**Comment by snpdev** [comment]
Probably would be good to run a validation/lint routine on the yaml output from ```helm template```, before using ```kubectl apply```.  @Schnitzel, does Lagoon have such a routine?

**Comment by Schnitzel** [comment]
@snpdev 
currently there is no such validation, if the template generates from yaml code the `kubectl apply` just fails and with that the whole build fails.
this was so far not a big issue, so I don't think we have to solve this then :)

**Comment by snpdev** [comment]
@Schnitzel, please refer to these lines of shell code in the SNP fork:
1. Add helm-template plugin: 
https://github.com/snp-technologies/lagoon/blob/97d7e522222c2b226adef92beef0cec0e89e9348/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L656-L659 

2. Use `helm template` to create yaml manifest, and apply the manifest:
https://github.com/snp-technologies/lagoon/blob/97d7e522222c2b226adef92beef0cec0e89e9348/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L684-L699

This seems to work fine in initial testing (thanks @siva2krish).

Note the use of the `$SERVICE_NAME` variable for the release name, which may not be the convention to follow.

**Comment by smlx** [comment]
Lagoon uses `helm` for k8s deployments now.
