### ISSUE TITLE
allow the ability of having plugable services. 

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#98]
It would be very useful to be able to extend / replace services in lagoon.

Opening this issue to discuss the viability / options around doing this.

This may require a service definition file to be created so we're able to define overrides to services -- https://github.com/amazeeio/lagoon/tree/master/services

I'll be looking into this as a priority since we need the flexibility to cleanly extend lagoon without the need to push everything upstream.

**Comment by thom8** [comment]
I assume services can be extended and or replaced inside -- https://github.com/amazeeio/lagoon/blob/develop/docker-compose.yaml

**Comment by Schnitzel** [comment]
@thom8 correct, that is probably the best place to do it:
- fork the repo
- remove or add new services to the `docker-compose.yaml` which will be used during a deployment.

Actually for each Project you can define an `deploy` and `remove` system. Which means you could have multiple systems that are responsible for a deployment and the removal of code. 
This happens here: https://github.com/amazeeio/lagoon/blob/develop/local-dev/api-data/api-data.sql#L56 (see the `lagoon_openshiftBuildDeploy` and `lagoon_openshiftRemove`).
Which then are switch/cased here:
https://github.com/amazeeio/lagoon/blob/develop/node-packages/commons/src/tasks.js#L119 (for deploy)
https://github.com/amazeeio/lagoon/blob/develop/node-packages/commons/src/tasks.js#L176 (for remove).

which both at the end just create a new message in the `builddeploy-openshift` and `remove-openshift` rabbitmq Queues. These Messages are then picked up by the two services called:
`OpenShiftBuildDeploy` https://github.com/amazeeio/lagoon/blob/develop/services/openshiftbuilddeploy/src/index.js#L377
`OpenShiftRemove`  https://github.com/amazeeio/lagoon/blob/develop/services/openshiftremove/src/index.js#L124
and handled.

So the system that decides how a project is deployed and removed is completely pluggable. Telling Lagoon to deploy to Kubernetes instead of OpenShift would mean:
1. create a new service that can handle deployments to Kubernetes
2. teach the commons/tasks about this service
3. define that this service should be use in the API
4. deploy :)

It's definitely a bit rough to add a new service and could use some love, but it's here!

**Comment by thom8** [comment]
Thanks @Schnitzel

Looks like we're able to make a start here and will raise a separate issue for anything else.
